return {
-- new name
	cordragate = {
		blocking = true,
		buildpic = "CORDRAG.DDS",
		buildtime = 255,
        canfly = true,
		canattack = false,
        --canmove IS needed to lift<
        canmove = true,
		canrepeat = false,
        --used for height<
        cruisealtitude = 75,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "32 22 32",
		collisionvolumetype = "CylY",
		corpse = "ROCKTEETH",
		crushresistance = 250,
		energycost = 0,
		explodeas = "WallExplosionMetal",
		footprintx = 2,
		footprintz = 2,
		health = 2800,
        -- maxacc = 0.1,
		-- maxdec = 0.75,
		-- maxslope = 10,
		hidedamage = true,
		levelground = false,
		maxacc = 0,
		maxdec = 0,
		maxslope = 64,
		maxwaterdepth = 0,
		metalcost = 8,
        -- new objectname
		objectname = "Units/cordragate.s3o",
		repairable = false,
        -- new script
		script = "Units/cordragate.cob",
		seismicsignature = 0,
		selfdestructas = "WallExplosionMetal",
		selfdestructcountdown = 1,
		sightdistance = 1,
		yardmap = "ffff",
        -- how quick it rises
        -- verticalspeed = 3.75,
        -- divided by 2
        verticalspeed = 1.875,
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 4,
			buildinggrounddecalsizey = 4,
            -- new
			buildinggrounddecaltype = "decals/cordragate_aoplane.dds",
			model_author = "Cremuss",
			normaltex = "unittextures/cor_normal.dds",
			objectify = true,
			paralyzemultiplier = 0,
			removestop = true,
			removewait = true,
			subfolder = "CorBuildings/LandUtil",
			unitgroup = "util",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			rockteeth = {
				animating = 0,
				animtrans = 0,
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				crushresistance = 0,
				damage = 500,
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 2,
				object = "Units/cor1X1A.s3o",
				reclaimable = true,
				resurrectable = 0,
				shadtrans = 1,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
			},
		},
	},
}
