return {
	corbarrel = {
		buildpic = "CORBARREL.DDS",
		buildtime = 15000,
		canmove = true,
		collisionvolumeoffsets = "0 0 -2",
		collisionvolumescales = "32 34 30",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 9300,
		explodeas = "mediumexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 5940,
		maxacc = 0.138,
		maxdec = 0.6486,
		maxslope = 14,
		maxwaterdepth = 21,
		metalcost = 560,
		movementclass = "BOT2",
		nochasecategory = "VTOL",
		objectname = "Units/corbarrel.s3o",
		script = "Units/corbarrel.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 380,
		speed = 37.5,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.825,
		turnrate = 1115.5,
		upright = true,
		customparams = {
			model_author = "LitLuigi73",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorGantry",
			techlevel = 3,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.220962524414 -3.57609763184 -0.162803649902",
				collisionvolumescales = "39.2589111328 21.1636047363 24.3341522217",
				collisionvolumetype = "Box",
				damage = 3500,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				metal = 339,
				object = "Units/corbarrel_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 2500,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 136,
				object = "Units/cor2X2F.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			corbhmth_weapon = {
				accuracy = 780,
				areaofeffect = 192,
				avoidfeature = false,
				cegtag = "arty-extraheavy",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.85,
				energypershot = 150,
				explosiongenerator = "custom:genericshellexplosion-large-bomb",
				firestarter = 99,
				gravityaffected = "true",
				impulsefactor = 0.8,
				name = "Heavy g2g barrage plasma battery",
				noselfdamage = true,
				range = 1650,
				reloadtime = 4.166,
				soundhit = "xplonuk5",
				soundhitvolume = 30,
				soundhitwet = "splslrg",
				soundstart = "xplolrg5",
				soundstartvolume = 20,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 620,
				damage = {
					default = 450,
					subs = 150,
					vtol = 110,
				},
			},
		},
		weapons = {
    		[1] = {
    			badtargetcategory = "VTOL",
    			def = "CORBHMTH_WEAPON",
    			onlytargetcategory = "SURFACE",
    		},
    		[2] = {
    			badtargetcategory = "VTOL",
    			def = "CORBHMTH_WEAPON",
    			onlytargetcategory = "SURFACE",
    		},
    		[3] = {
    			badtargetcategory = "VTOL",
    			def = "CORBHMTH_WEAPON",
    			onlytargetcategory = "SURFACE",
    		},
		},
	},
}
