return {
	corant = {
        autoheal = 10,
		buildpic = "CORTERMITE.DDS",
		buildtime = 13500,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "40 26 48",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energycost = 8100,
		explodeas = "mediumexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		health = 1550,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.19665,
		maxdec = 0.60375,
		maxslope = 50,
		maxwaterdepth = 30,
		metalcost = 540,
		movementclass = "TBOT3",
		mygravity = 10000,
		nochasecategory = "VTOL",
		objectname = "Units/CORANT.s3o",
		script = "Units/CORANT.cob",
		seismicsignature = 0,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 380,
		speed = 80,
        stealth = true,
		strafetoattack = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.0626,
		turnrate = 1214.40002,
		usepiececollisionvolumes = 1,
		customparams = {
			model_author = "Beherith",
			normaltex = "unittextures/cor_normal.dds",
			paralyzemultiplier = 0.2,
			subfolder = "CorBots/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 -1.2 0",
				collisionvolumescales = "26 12 43",
				collisionvolumetype = "Box",
				damage = 2000,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 10,
				metal = 523,
				object = "Units/CORANT_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "55.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 1500,
				footprintx = 3,
				footprintz = 3,
				metal = 209,
				object = "Units/cor3X3A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
            explosiongenerators = {
				[1] = "custom:flamestreamxm",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "spider2",
			},
			select = {
				[1] = "spider",
			},
		},
		weapondefs = {
			dmaw = {
				areaofeffect = 64,
				avoidfeature = false,
				burst = 16,
				burstrate = 0.05,
				cegtag = "burnflame-anim",
				colormap = "1 0.95 0.82 0.03   0.65 0.4 0.35 0.030   0.44 0.25 0.20 0.028   0.033 0.018 0.012 0.03   0.0 0.0 0.0 0.01",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:burnblack",
				firestarter = 100,
				flamegfxtime = 1,
				impulsefactor = 0,
				intensity = 0.68,
				name = "anti-swarm AoE flamethrower",
				noselfdamage = true,
				proximitypriority = 1,
				range = 350,
				-- range = 410,
				reloadtime = 1.1,
				rgbcolor = "1 0.94 0.88",
				rgbcolor2 = "0.9 0.84 0.8",
				sizegrowth = 0.50,
				-- sizegrowth = 0.75,
				soundhitdry = "flamhit1",
				soundhitvolume = 7.5,
				soundhitwet = "sizzle",
				soundstart = "Flamhvy1",
				soundstartvolume = 5.3,
				soundtrigger = false,
				sprayangle = 100,
				targetmoveerror = 0.001,
				texture1 = "flame",
				tolerance = 2500,
				turret = true,
				weapontimer = 1,
				weapontype = "Flame",
				weaponvelocity = 300,
				customparams = {
					exclude_preaim = false,
				},
				damage = {
					default = 22,
					subs = 5.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "DMAW",
				onlytargetcategory = "SURFACE",
			},
		},
	},
}
