return {
	armspwe = {
		autoheal = 10,
		builddistance = 214,
		builder = true,
		buildpic = "ARMSPID.DDS",
		buildtime = 5100,
        canassist = true,
		canmove = true,
		canrepair = true,
		canrestore = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "28 15 28",
		collisionvolumetype = "box",
		corpse = "DEAD",
		energycost = 7000,
		explodeas = "smallexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		health = 1210,
		idleautoheal = 5,
		idletime = 600,
		maxacc = 0.207,
		maxdec = 0.6486,
		maxwaterdepth = 16,
		metalcost = 275,
		movementclass = "TBOT3",
		mygravity = 10000,
		nochasecategory = "ALL",
		objectname = "Units/ARMSPWE.s3o",
		script = "Units/ARMSPWE.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 550,
		speed = 65,
		stealth = false,
		strafetoattack = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.749,
		turnrate = 1290.29993,
		workertime = 150,
		buildoptions = {
			[1] = "armmine2",
			[2] = "armmine3",
			[3] = "armdrag",
			[4] = "armeyes",
			[5] = "armferret",
			[6] = "armguard",
            [7] = "armjamt",
            [8] = "armrad",
            [9] = "armmex",
            [10] = "armgroundhog",
            [11] = "armamex",
            [12] = "armclaw",
            [13] = "armspid",
            [14] = "armsptk",
		},
        customparams = {
            minesweeper = 400,
			model_author = "Kaiser",
			normaltex = "unittextures/Arm_normal.dds",
			paralyzemultiplier = 0.2,
			selectable_as_combat_unit = true,
			subfolder = "ArmBots/T2",
			techlevel = 2,
			unitgroup = "builder",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.0926513671875 -4.24316406278e-06 -0.909057617188",
				collisionvolumescales = "31.362487793 12.4340515137 31.2150268555",
				collisionvolumetype = "Box",
				damage = 600,
				featuredead = "HEAP",
				footprintx = 2,
				footprintz = 2,
				height = 40,
				metal = 108,
				object = "Units/armspwe_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "35.0 4.0 6.0",
				collisionvolumetype = "cylY",
				damage = 400,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 43,
				object = "Units/arm2X2A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
            capture = "capture1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "spider2",
			},
			select = {
				[1] = "spider",
			},
		},
		  weapondefs = {
              minesweep = {
				  areaofeffect = 255,
				  avoidfeature = false,
				  collidefriendly = false,
				  craterareaofeffect = 48,
				  craterboost = 0,
				  cratermult = 0,
				  edgeeffectiveness = 0.5,
				  -- explosiongenerator = "custom:MINESWEEP",
				  firetolerance = 3000,
				  gravityaffected = "true",
				  name = "Seismic charge",
				  soundhit = "xplomed4",
                  soundhitwet = "splslrg",
                  soundstart = "cannhvy2",
                  impulsefactor = 8.5,
                  noselfdamage = true,
				  range = 500,
				  reloadtime = 3.0,
				  rgbcolor = "0.2 0.6 0.2",
				  tolerance = 3000,
				  turret = true,
				  weapontimer = 0.1,
				  weapontype = "Cannon",
				  weaponvelocity = 330,
				  damage = {
					  default = 5,
				  },
			    },
		  shortrangemissile = {
				areaofeffect = 24,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				castshadow = false,
				cegtag = "missiletrailaa",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-tiny-aa",
				firestarter = 70,
				fixedlauncher = true,
				flighttime = 1.85,
				impulsefactor = 0,
				metalpershot = 0,
				model = "cormissile.s3o",
				name = "Medium-Range Anti-Air Missile Launcher",
				noselfdamage = true,
				proximitypriority = 1,
				range = 880,
				reloadtime = 0.7,
				smokecolor = 1,
				smokeperiod = 6,
				smokesize = 2,
				smoketime = 11,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "xplosml2",
				soundhitvolume = 7.5,
				soundhitwet = "splshbig",
				soundstart = "rocklit1",
				soundstartvolume = 7.5,
				startvelocity = 100,
				texture1 = "null",
				texture2 = "smoketrailaa",
				tolerance = 26000,
				tracks = true,
				turnrate = 30000,
				turret = true,
				weaponacceleration = 400,
				weapontimer = 5,
				weapontype = "MissileLauncher",
				weaponvelocity = 800,
				damage = {
					vtol = 100,
				},
            },
        },    
		  weapons = {
			  [1] = {
				  def = "MINESWEEP",
				  -- maindir = "0 0 1",
				  -- maxangledif = 300,
				  onlytargetcategory = "SURFACE",
                },    
              [2] = {
				  badtargetcategory = "NOTAIR LIGHTAIRSCOUT",
                  def = "SHORTRANGEMISSILE",
				  onlytargetcategory = "VTOL",
            
                  },
            },
        },
    }
